default_context:
  project_name: 'fastapi-demo'
  project_slug: 'fastapi-demo'
  domain_main: 'fastapi-demo.com'
  domain_staging: 'stag.fastapi-demo.com'
  docker_swarm_stack_name_main: 'fastapi-demo-com'
  docker_swarm_stack_name_staging: 'stag-fastapi-demo-com'
  secret_key: '81a81fcff480b9bfce544b17607a51ad893477cb794517185ee2e94de5f3c096'
  first_superuser: 'admin@fastapi-demo.com'
  first_superuser_password: '01205d6e1eff90a33c16e27c0440dea0c0b6258f9389a28b2401096869ccd84f'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.fastapi-demo.com", "https://stag.fastapi-demo.com", "https://fastapi-demo.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@fastapi-demo.com'
  postgres_password: 'f8c3371ab8ebe27cf51fbe4cd3336921166961a748fbf7ca3887c260b2fa72a1'
  pgadmin_default_user: 'admin@fastapi-demo.com'
  pgadmin_default_user_password: '01205d6e1eff90a33c16e27c0440dea0c0b6258f9389a28b2401096869ccd84f'
  traefik_constraint_tag: 'fastapi-demo.com'
  traefik_constraint_tag_staging: 'stag.fastapi-demo.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:01205d6e1eff90a33c16e27c0440dea0c0b6258f9389a28b2401096869ccd84f'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
